# SPDX-FileCopyrightText: 2025 Qingcheng.AI
#
# SPDX-License-Identifier: Apache-2.0

backend: 
- model: 'deepseek'
  rules:
    - regex : 'layers\.(\d+)\.mlp\.moe'
      backend: cpuinfer
      layers: ["3-60"]
