# SPDX-FileCopyrightText: 2025 Qingcheng.AI
#
# SPDX-License-Identifier: Apache-2.0

backend:
- model: 'deepseek'
  rules:
    - regex : 'layers\.(\d+)\.mlp\.moe'
      layers: ["3-40"]
      backend: cpuinfer
    - regex: '\.mlp.experts\.'
      layers: ["3-40"]
      backend: cpuinfer
- model: 'qwen'
  rules:
    - regex : 'layers\.(\d+)\.mlp'
      layers: ["3-20"]
      backend: cpuinfer