# SPDX-FileCopyrightText: 2025 Qingcheng.AI
#
# SPDX-License-Identifier: Apache-2.0

# DeepSeek-R1-FP4 is a data-type variant of DeepSeek-R1
defaults:
  - DeepSeek-R1
  - override quant_config: blockfp4
  - _self_ # Config in this file overrides configs in defaults

# Access info
name: DeepSeek-R1-FP4
source: "https://huggingface.co/nvidia/DeepSeek-R1-FP4" # Just for displaying. No automatic download.
ckpt_dir: null # Please override this in commond line with `models.ckpt_dir=<path>`.
tokenizer_path: null # By default the same as ckpt_dir, or you can override it with `models.tokenizer_path=<path>`.

# Overrides
main_weight_dtype: float4_e2m1
