# SPDX-FileCopyrightText: 2025 Qingcheng.AI
#
# SPDX-License-Identifier: Apache-2.0

# DeepSeek-V3.1 shares the same model structure with DeepSeek-V3
defaults:
  - DeepSeek-V3
  - _self_ # Config in this file overrides configs in defaults

# Access info
name: DeepSeek-V3.1
source: "https://huggingface.co/deepseek-ai/DeepSeek-V3.1" # Just for displaying. No automatic download.
ckpt_dir: null # Please override this in commond line with `models.ckpt_dir=<path>`.
tokenizer_path: null # By default the same as ckpt_dir, or you can override it with `models.tokenizer_path=<path>`.
tokenizer_type: "hf" # one of: hf, tiktoken