# SPDX-FileCopyrightText: 2025 Qingcheng.AI
#
# SPDX-License-Identifier: Apache-2.0

# DeepSeek-R1 is a finetune of DeepSeek-V3
defaults:
  - DeepSeek-V3
  - _self_ # Config in this file overrides configs in defaults

# Access info
name: DeepSeek-R1
source: "https://huggingface.co/deepseek-ai/DeepSeek-R1" # Just for displaying. No automatic download.
ckpt_dir: null # Please override this in commond line with `models.ckpt_dir=<path>`.
tokenizer_path: null # By default the same as ckpt_dir, or you can override it with `models.tokenizer_path=<path>`.
