# SPDX-FileCopyrightText: 2025 Qingcheng.AI
#
# SPDX-License-Identifier: Apache-2.0

name: glm-z1-32b
type: hf-glm-z1
source: "https://modelscope.cn/models/ZhipuAI/GLM-Z1-32B-0414/" # Just for displaying. No automatic download.
ckpt_dir: null # Please override this in commond line with `models.ckpt_dir=<path>`.
tokenizer_path: null # By default the same as ckpt_dir, or you can override it with `models.tokenizer_path=<path>`.
tokenizer_type: "hf" # one of: hf, tiktoken
dim: 6144
n_layers: 61
n_heads: 48
n_kv_heads: 2
vocab_size: 151552
intermediate_dim: 23040
norm_eps: 1e-05
rope_theta: 10000.0
qkv_has_bias: False
