# SPDX-FileCopyrightText: 2025 Qingcheng.AI
#
# SPDX-License-Identifier: Apache-2.0

name: gpt-oss-120b-BF16
type: hf-gpt-oss
source: "https://huggingface.co/unsloth/gpt-oss-120b-BF16" # Just for displaying. No automatic download.
ckpt_dir: null # Please override this in commond line with `models.ckpt_dir=<path>`.
tokenizer_path: null # By default the same as ckpt_dir, or you can override it with `models.tokenizer_path=<path>`.
tokenizer_type: "hf" # one of: hf, tiktoken
dim: 2880
n_layers: 36
n_heads: 64
n_kv_heads: 8
vocab_size: 201088
intermediate_dim: 2880
moe_intermediate_dim: 2880
num_experts: 128
num_experts_per_tok: 4
norm_topk_prob: False
norm_eps: 1e-05
rope_theta: 150000.0
qkv_has_bias: True
o_has_bias: True
head_dim: 64
eos_token_id: 200002
