# SPDX-FileCopyrightText: 2025 Qingcheng.AI
#
# SPDX-License-Identifier: Apache-2.0

name: Qwen2.5-7B
type: hf-llama
source: "https://huggingface.co/Qwen/Qwen2.5-7B" # Just for displaying. No automatic download.
ckpt_dir: null # Please override this in commond line with `models.ckpt_dir=<path>`.
tokenizer_path: null # By default the same as ckpt_dir, or you can override it with `models.tokenizer_path=<path>`.
tokenizer_type: "hf" # one of: hf, tiktoken
dim: 3584
n_layers: 28
n_heads: 28
n_kv_heads: 4
vocab_size: 152064
intermediate_dim: 18944
norm_eps: 1e-06
rope_theta: 1000000.0
