# SPDX-FileCopyrightText: 2025 Qingcheng.AI
#
# SPDX-License-Identifier: Apache-2.0

name: Qwen3-32B
type: hf-llama
source: "https://huggingface.co/Qwen/Qwen3-32B" # Just for displaying. No automatic download.
ckpt_dir: null # Please override this in commond line with `models.ckpt_dir=<path>`.
tokenizer_path: null # By default the same as ckpt_dir, or you can override it with `models.tokenizer_path=<path>`.
tokenizer_type: "hf" # one of: hf, tiktoken
dim: 5120
n_layers: 64
n_heads: 64
n_kv_heads: 8
vocab_size: 151936
intermediate_dim: 25600
norm_eps: 1e-06
rope_theta: 1000000.0
qkv_has_bias: False
head_dim: 128
use_qk_norm: True
