# SPDX-FileCopyrightText: 2025 Qingcheng.AI
#
# SPDX-License-Identifier: Apache-2.0

# Qwen2.5-32B-Instruct is a finetune of Qwen2.5-32B
defaults:
  - Qwen2.5-32B
  - _self_ # Config in this file overrides configs in defaults

# Access info
name: Qwen2.5-32B-Instruct
source: "https://huggingface.co/Qwen/Qwen2.5-32B-Instruct" # Just for displaying. No automatic download.
ckpt_dir: null # Please override this in commond line with `models.ckpt_dir=<path>`.
tokenizer_path: null # By default the same as ckpt_dir, or you can override it with `models.tokenizer_path=<path>`.
