# SPDX-FileCopyrightText: 2025 Qingcheng.AI
#
# SPDX-License-Identifier: Apache-2.0

name: Qwen3-235B-A22B
type: hf-qwen-3-moe
source: "https://huggingface.co/Qwen/Qwen3-235B-A22B" # Just for displaying. No automatic download.
ckpt_dir: null # Please override this in commond line with `models.ckpt_dir=<path>`.
tokenizer_path: null # By default the same as ckpt_dir, or you can override it with `models.tokenizer_path=<path>`.
tokenizer_type: "hf" # one of: hf, tiktoken
dim: 4096
n_layers: 94
n_heads: 64
n_kv_heads: 4
vocab_size: 151936
intermediate_dim: 12288
moe_intermediate_dim: 1536
num_experts: 128
num_experts_per_tok: 8
norm_topk_prob: True
norm_eps: 1e-06
rope_theta: 1000000.0
qkv_has_bias: False
head_dim: 128
use_qk_norm: True
