# SPDX-FileCopyrightText: 2025 Qingcheng.AI
#
# SPDX-License-Identifier: Apache-2.0

name: Qwen2.5-VL-7B-Instruct
type: hf-qwen2-vl
source: "https://huggingface.co/Qwen/Qwen2.5-VL-7B-Instruct" # Just for displaying. No automatic download.
tokenizer_type: "hf" # one of: hf, tiktoken
ckpt_dir: null # Please override this in commond line with `models.ckpt_dir=<path>`.
tokenizer_path: null # By default the same as ckpt_dir, or you can override it with `models.tokenizer_path=<path>`.
processor_path: null # By default the same as ckpt_dir, or you can override it with `models.processor_path=<path>`.

dim: 3584
n_heads: 28
n_kv_heads: 4
n_layers: 28
intermediate_dim: 18944
vocab_size: 152064
norm_eps: 1e-6
max_position_embeddings: 128000
rope_theta: 1000000.0

rope_scaling:
  rope_type: mrope
  mrope_section: [16, 24, 24]
  factor: 1.0

vision_config:
  depth: 32
  hidden_act: "silu"
  hidden_size: 1280
  intermediate_size: 3420
  num_heads: 16
  in_channels: 3
  out_hidden_size: 3584
  patch_size: 14
  spatial_merge_size: 2
  spatial_patch_size: 14
  window_size: 112
  fullatt_block_indexes: [7, 15, 23, 31]
  temporal_patch_size: 2
  vision_start_token_id: 151652
  image_token_id: 151655
  video_token_id: 151656
