# SPDX-FileCopyrightText: 2025 Qingcheng.AI
#
# SPDX-License-Identifier: Apache-2.0

# Qwen3-32B-fp4 is a quantization of Qwen3-32B
defaults:
  - Qwen3-32B
  - quant_config: blockfp4
  - _self_ # Config in this file overrides configs in defaults

# Access info
name: Qwen3-32B-fp4
source: "https://huggingface.co/qingcheng-ai/Qwen3-32B-fp4" # Just for displaying. No automatic download.
ckpt_dir: null # Please override this in commond line with `models.ckpt_dir=<path>`.
tokenizer_path: null # By default the same as ckpt_dir, or you can override it with `models.tokenizer_path=<path>`.

