# SPDX-FileCopyrightText: 2025 Qingcheng.AI
#
# SPDX-License-Identifier: Apache-2.0

# Qwen3-32B-w4a8-g128 is a quantization of Qwen3-32B
defaults:
  - Qwen3-32B
  - quant_config: w4a8_per_token_per_group_asymm
  - _self_ # Config in this file overrides configs in defaults

# Access info
name: Qwen3-32B-QServe-w4a8-g128
source: "(This is an internal quantized model, only for testing purpose)" # Just for displaying. No automatic download.
ckpt_dir: null # Please override this in commond line with `models.ckpt_dir=<path>`.
tokenizer_path: null # By default the same as ckpt_dir, or you can override it with `models.tokenizer_path=<path>`.

