# SPDX-FileCopyrightText: 2025 Qingcheng.AI
#
# SPDX-License-Identifier: Apache-2.0

# Qwen3-14B-FP8 is a quantization of Qwen3-14B
defaults:
  - Qwen3-14B
  - quant_config: blockfp8
  - _self_ # Config in this file overrides configs in defaults

# Access info
name: Qwen3-14B-FP8
source: "https://huggingface.co/Qwen/Qwen3-14B-FP8" # Just for displaying. No automatic download.
ckpt_dir: null # Please override this in commond line with `models.ckpt_dir=<path>`.
tokenizer_path: null # By default the same as ckpt_dir, or you can override it with `models.tokenizer_path=<path>`.
