# SPDX-FileCopyrightText: 2025 Qingcheng.AI
#
# SPDX-License-Identifier: Apache-2.0

# QwQ-32B-simple-w8a8-muxi is a quantization of QwQ-32B
defaults:
  - QwQ-32B
  - quant_config: simple_w8a8_muxi
  - _self_ # Config in this file overrides configs in defaults

# Access info
name: QwQ-32B-simple-w8a8-muxi
source: "(This is an internal quantized model, only for testing purpose)" # Just for displaying. No automatic download.
ckpt_dir: null # Please override this in commond line with `models.ckpt_dir=<path>`.
tokenizer_path: null # By default the same as ckpt_dir, or you can override it with `models.tokenizer_path=<path>`.
